### ISSUE TITLE
Unable to import pipeline

### ISSUE THREAD

**Issue by fathoni** [openbudgets/datasets#15]
Hi Sotiris, Babis,

I could not manage to import your pipelines (both for Athens and Thessaloniki). I have tried these both in my local installation and http://obeu.vse.cz/unifiedviews/#!Login . Can you please check?

**Comment by skarampatakis** [comment]
Hi @fathoni ,
I was able to import both ESIF pipeline and the Municipality of Thessaloniki Budget pipeline in our local installation. I found out that at  [yours](http://obeu.vse.cz/unifiedviews/#!Login) Municipality of Thessaloniki cannot imported because of `Wrong or missing pipeline file`. Also our UnifiedViews version is v2.3.0 while yours v2.2.0. Maybe this is the problem. Can you please check upgrading your installation.

**Comment by jakubklimek** [comment]
Hi guys,
This is a known problem with UnifiedViews that pipeline import/export only works with exactly the same version of UV itself and each DPU used in the pipeline.
(Actually, it is even a bit more complicated if you are using DPU templates)

Also, it is yet another reason to use LinkedPipes ETL for new pipelines.

The solution for UV is:
- Have the same UV version
- For DPUs, when the DPUs are packaged in the pipeline export, you can unzip it and replace each DPU in your instance with the DPU from the export, if that one is newer. You can do that in the DPU Templates tab, click on DPU you want to replace and there should be the replace button.

**Comment by fathoni** [comment]
Hi Sotiris and Jakub,

Thanks for the clarification, now I see the problem. I will close this issue.
