### ISSUE TITLE
eu-dimension:reservedFor codelist

### ISSUE THREAD

**Issue by larjohn** [openbudgets/datasets#21]
In EU budget 2014, there are observations with dimensions like that:

eu-dimension:reservedFor http://data.openbudgets.eu/resource/dataset/budget-of-the-european-union-2014/observation/EU/commitment/ADOPTED/2014/3-article-01-02-01/1.1.SPEC ;

Do we have a codelist for this one?

**Comment by jindrichmynarz** [comment]
No, there is no code list for the `eu-dimension:reservedFor`. This dimension is used in a special data cube for reserves. Each budget line in the budget of the European Union can have a reserve. The objects of `eu-dimension:reservedFor` (`rdfs:range qb:Observation`) are therefore the budget lines for which the reserve can be used. In a sense, you can treat the set of budget lines as the code list of this dimension (and indeed strict interpretation of DCV would probably require casting the budget lines as `skos:Concept`s).

**Comment by larjohn** [comment]
Alright, thing is that it would be nice if there was a label for these lines, or some other attribute to display.

**Comment by jindrichmynarz** [comment]
How would you propose to create such labels? One option could be in line with how we create IRIs for `qb:Observation`s. Instead of concatenating `skos:notation`s of objects of dimensions, we can concatenate `skos:prefLabel`s of these objects. However, doing so would get unwieldy.

What I'd suggest instead is to just use labels of the objects of the budgeting nomenclature (i.e. `eu-dimension:budgetNomenclature/skos:prefLabel`) as probably the most significant dimension characterizing the budget line. Nevertheless, these labels do no uniquely identify budget lines and there would be multiple budget lines per single budgeting nomenclature (e.g., for different fiscal years or budget phases).

**Comment by larjohn** [comment]
The ideal way would be to have the actual reserves in our dataset, with the appropriate URI's. Then we could select their properties as required. 
The main concern is the presentation of these values in OpenSpending's UI, where they are 'dumped' as URI's, because they have no other property.

**Comment by jindrichmynarz** [comment]
You have the actual reserves in the dataset. The dataset contains 2 instances of `qb:DataSet`:
1. `<http://data.openbudgets.eu/resource/dataset/budget-of-the-european-union-2014>`: budget lines
2. `<http://data.openbudgets.eu/resource/dataset/budget-of-the-european-union-2014/reserves>`: reserves associated to budget lines

Reserves are modelled as instances of `qb:Observation` and are identified with IRIs. If I understand correctly, and the problem with observations in OpenSpending UI is that they don't have any labels, then it applies not only to reserves, but to budget or spending lines too.
