### ISSUE TITLE
Codelist missing labels

### ISSUE THREAD

**Issue by skarampatakis** [openbudgets/datasets#82]
@jindrichmynarz 
The codelist [esf_2007_2013_czech_operational_programmes.ttl](https://github.com/openbudgets/datasets/blob/master/ESF-CZ/2007-2013/projects/codelists/esf_2007_2013_czech_operational_programmes.ttl) has missing labels. Could you please add them?

Also, Concept Scheme IRI seems to be wrong. On top concepts it is referred as ns:operationalProgramme while in the Scheme definition is referred as ns:operational-programme.

**Comment by jindrichmynarz** [comment]
Unfortunately, the source data has no labels for non-leaf concepts. I can add synthetic labels if you want (i.e. the same as `skos:notation`).

**Comment by jindrichmynarz** [comment]
The invalid IRIs in the code list were fixed. Missing labels are not present in the source dataset. We tried to find the code list for operational programmes in the Czech Republic, but so far without success. The data about the breakdowns of operational programmes are scattered in HTML across many web pages. Our colleague Lucie tried to piece them together, but didn't finish it, since it was complicated to find all necessary information. However, if this is deemed as important, please re-open this issue and we'll invest more effort into it.

**Comment by skarampatakis** [comment]
Thank you for the update. About importance, this is on the team involved in the linking project to decide.
